# Generated by Django 5.1.15 on 2026-02-15 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_calendarfeedtoken_meeting'),
        ('programs', '0008_funder_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='owning_program',
            field=models.ForeignKey(blank=True, help_text='Program that owns this event type. Null = global (admin-created).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='programs.program'),
        ),
    ]
