# Generated by Django 6.0.1 on 2026-02-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_add_follow_up_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='participant_reflection',
            field=models.TextField(blank=True, default='', help_text="The participant's own words about what they're taking away from the session."),
        ),
    ]
