# Generated by Django 6.0.1 on 2026-02-05 17:50
"""
SEC1: Progress Note Encryption

WARNING: This migration REMOVES existing text fields and replaces them with
encrypted BinaryFields. Any existing progress note content will be LOST.

This is acceptable for initial deployment where no production data exists.
DO NOT apply this migration to a database with real data without first
running a data migration to encrypt existing content.

If you need to migrate existing data, create an intermediate migration that:
1. Adds the new encrypted fields (without removing old ones)
2. Copies and encrypts data from old fields to new fields
3. Then removes the old fields in a subsequent migration
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_add_participant_reflection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressnote',
            name='notes_text',
        ),
        migrations.RemoveField(
            model_name='progressnote',
            name='participant_reflection',
        ),
        migrations.RemoveField(
            model_name='progressnote',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='progressnotetarget',
            name='notes',
        ),
        migrations.AddField(
            model_name='progressnote',
            name='_notes_text_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='_participant_reflection_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='_summary_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='progressnotetarget',
            name='_notes_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
