# Generated by Django 6.0.1 on 2026-02-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_encrypt_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='interaction_type',
            field=models.CharField(choices=[('session', 'One-on-One Session'), ('group', 'Group Session'), ('phone', 'Phone Call'), ('collateral', 'Contact with Others'), ('home_visit', 'Home Visit'), ('admin', 'Admin / Paperwork'), ('other', 'Other')], default='session', max_length=20),
        ),
        migrations.AddField(
            model_name='progressnotetemplate',
            name='default_interaction_type',
            field=models.CharField(choices=[('session', 'One-on-One Session'), ('group', 'Group Session'), ('phone', 'Phone Call'), ('collateral', 'Contact with Others'), ('home_visit', 'Home Visit'), ('admin', 'Admin / Paperwork'), ('other', 'Other')], default='session', help_text='Pre-fills the interaction type when this template is selected.', max_length=20),
        ),
    ]
