# Generated by Django 5.1.15 on 2026-02-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_progressnotetemplate_owning_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', '---------'), ('reached', 'Reached'), ('left_message', 'Left Message'), ('no_answer', 'No Answer')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='progressnote',
            name='interaction_type',
            field=models.CharField(choices=[('session', 'One-on-One Session'), ('group', 'Group Session'), ('phone', 'Phone Call'), ('sms', 'Text Message'), ('email', 'Email'), ('collateral', 'Contact with Others'), ('home_visit', 'Home Visit'), ('admin', 'Admin / Paperwork'), ('other', 'Other')], db_index=True, default='session', max_length=20),
        ),
        migrations.AlterField(
            model_name='progressnotetemplate',
            name='default_interaction_type',
            field=models.CharField(choices=[('session', 'One-on-One Session'), ('group', 'Group Session'), ('phone', 'Phone Call'), ('sms', 'Text Message'), ('email', 'Email'), ('collateral', 'Contact with Others'), ('home_visit', 'Home Visit'), ('admin', 'Admin / Paperwork'), ('other', 'Other')], default='session', help_text='Pre-fills the interaction type when this template is selected.', max_length=20),
        ),
    ]
