# Generated by Django 5.1.15 on 2026-02-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_add_outcome_and_contact_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressnote',
            name='note_type',
            field=models.CharField(choices=[('quick', 'Quick Note'), ('full', 'Detailed Note')], max_length=20),
        ),
    ]
