# Generated by Django 5.1.15 on 2026-02-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_rename_full_note_to_detailed_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnotetemplate',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='French name (displayed when language is French)', max_length=255),
        ),
        migrations.AddField(
            model_name='progressnotetemplatesection',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='French name (displayed when language is French)', max_length=255),
        ),
    ]
