# Generated by Django 5.1.15 on 2026-02-13 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0020_clientfile__email_encrypted_and_more'),
        ('programs', '0008_funder_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('in_person', 'In Person'), ('portal', 'Portal Message'), ('whatsapp', 'WhatsApp')], max_length=15)),
                ('method', models.CharField(choices=[('manual_log', 'Manual Log'), ('system_sent', 'System Sent'), ('system_received', 'System Received')], default='manual_log', max_length=15)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('_content_encrypted', models.BinaryField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('blocked', 'Blocked')], default='sent', max_length=15)),
                ('delivery_status_display', models.CharField(blank=True, default='', help_text='Plain-language description of delivery result for staff display', max_length=255)),
                ('external_id', models.CharField(blank=True, default='', help_text='External reference (e.g. Twilio SID)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program')),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='clients.clientfile')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_file', '-created_at'], name='communicati_client__99a06a_idx'), models.Index(fields=['delivery_status'], name='communicati_deliver_bd7d73_idx')],
            },
        ),
    ]
