# Generated by Django 5.1.15 on 2026-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_communication_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='method',
            field=models.CharField(choices=[('manual_log', 'Manual Log'), ('staff_sent', 'Staff Sent'), ('system_sent', 'System Sent'), ('system_received', 'System Received')], default='manual_log', max_length=15),
        ),
    ]
