# Generated by Django 5.1.15 on 2026-02-16 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_fix_contact_field_ordering'),
        ('communications', '0004_alter_communication_method'),
        ('programs', '0008_funder_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_content_encrypted', models.BinaryField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('author_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program')),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_messages', to='clients.clientfile')),
                ('for_user', models.ForeignKey(blank=True, help_text='Staff member this message is for. Blank = any case worker on this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('left_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_file', '-created_at'], name='staff_messa_client__d2ee4f_idx'), models.Index(fields=['for_user', 'status', '-created_at'], name='staff_messa_for_use_14afde_idx')],
            },
        ),
    ]
