# Generated by Django 6.0.1 on 2026-02-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_rename_receptionist_access_to_front_desk_access'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_group_client_file',
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('client_file__isnull', False), ('status', 'active')), fields=('group', 'client_file'), name='unique_group_client_file'),
        ),
    ]
