# Generated by Django 5.1.15 on 2026-02-10 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_staffportalnote'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPortalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_content_encrypted', models.BinaryField(default=b'')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_portal_notes', to='clients.clientfile')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_notes_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff portal note',
                'verbose_name_plural': 'staff portal notes',
                'db_table': 'portal_staff_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
