# Generated by Django 6.0.1 on 2026-02-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_userprogramrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Confidential programs are invisible to staff in other programs. Cannot be changed back to Standard without a formal Privacy Impact Assessment.'),
        ),
    ]
