# Generated by Django 5.1.15 on 2026-02-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_metricdefinition_portal_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='portal_description',
            field=models.TextField(blank=True, default='', help_text='Plain-language explanation shown to participants in the portal. Describe what the metric measures and what the numbers mean.'),
        ),
    ]
