# Generated by Django 5.1.15 on 2026-02-15 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_metricdefinition_portal_description'),
        ('programs', '0008_funder_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantemplate',
            name='owning_program',
            field=models.ForeignKey(blank=True, help_text='Program that owns this template. Null = global (admin-created).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_templates', to='programs.program'),
        ),
    ]
