# Generated by Django 5.1.15 on 2026-02-15 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_plantemplate_owning_program'),
        ('programs', '0008_funder_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='owning_program',
            field=models.ForeignKey(blank=True, help_text='Program that owns this metric. Null = global (admin-created or library).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_definitions', to='programs.program'),
        ),
    ]
