# Generated by Django 5.1.15 on 2026-02-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_metricdefinition_owning_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='definition_fr',
            field=models.TextField(blank=True, default='', help_text='French definition (displayed when language is French)'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='French name (displayed when language is French)', max_length=255),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='portal_description_fr',
            field=models.TextField(blank=True, default='', help_text='French portal description (displayed when language is French)'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='unit_fr',
            field=models.CharField(blank=True, default='', help_text="French unit label (e.g., 'pointage', 'jours', '%')", max_length=50),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='description_fr',
            field=models.TextField(blank=True, default='', help_text='French description (displayed when language is French)'),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='French name (displayed when language is French)', max_length=255),
        ),
        migrations.AddField(
            model_name='plantemplatesection',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='French name (displayed when language is French)', max_length=255),
        ),
        migrations.AddField(
            model_name='plantemplatetarget',
            name='description_fr',
            field=models.TextField(blank=True, default='', help_text='French description (displayed when language is French)'),
        ),
        migrations.AddField(
            model_name='plantemplatetarget',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='French name (displayed when language is French)', max_length=255),
        ),
    ]
