"""
Custom field values for demo clients (DEMO-001 through DEMO-010).

Shared between seed_demo_data and update_demo_client_fields so that
the data stays in sync. Field names must match those in seed_intake_fields.py.
"""

CLIENT_CUSTOM_FIELDS = {
    "DEMO-001": {
        "Preferred Name": "Jordan",
        "Primary Phone": "(416) 555-0123",
        "Email": "jordan.rivera@example.com",
        "Preferred Contact Method": "Text message",
        "Best Time to Contact": "Afternoon (12pm-5pm)",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "Maria Rivera",
        "Emergency Contact Relationship": "Parent/Guardian",
        "Emergency Contact Phone": "(416) 555-0124",
        "Referral Source": "Community agency",
        "Referring Agency Name": "Downtown Community Health Centre",
    },
    "DEMO-002": {
        "Preferred Name": "Taylor",
        "Primary Phone": "(647) 555-0234",
        "Preferred Contact Method": "Phone call",
        "Best Time to Contact": "Morning (9am-12pm)",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "Alex Chen",
        "Emergency Contact Relationship": "Friend",
        "Emergency Contact Phone": "(647) 555-0235",
        "Referral Source": "Shelter/Housing provider",
        "Referring Agency Name": "Covenant House",
        "Accommodation Needs": "Prefers written appointment reminders",
    },
    "DEMO-003": {
        "Preferred Name": "Avery",
        "Primary Phone": "(905) 555-0345",
        "Email": "avery.j@example.com",
        "Preferred Contact Method": "Email",
        "Best Time to Contact": "Any time",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "Jamie Johnson",
        "Emergency Contact Relationship": "Sibling",
        "Emergency Contact Phone": "(905) 555-0346",
        "Referral Source": "Hospital/Health provider",
        "Referring Agency Name": "CAMH",
    },
    "DEMO-004": {
        "Primary Phone": "(416) 555-0456",
        "Preferred Contact Method": "Text message",
        "Best Time to Contact": "Evening (5pm-8pm)",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "Priya Patel",
        "Emergency Contact Relationship": "Parent/Guardian",
        "Emergency Contact Phone": "(416) 555-0457",
        "Referral Source": "School/Education",
        "Referring Agency Name": "Toronto District School Board",
    },
    "DEMO-005": {
        "Preferred Name": "Sam",
        "Primary Phone": "(647) 555-0567",
        "Email": "sam.williams@example.com",
        "Preferred Contact Method": "Email",
        "Best Time to Contact": "Any time",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "Drew Williams",
        "Emergency Contact Relationship": "Spouse/Partner",
        "Emergency Contact Phone": "(647) 555-0568",
        "Referral Source": "Self-referral",
    },
    "DEMO-006": {
        "Primary Phone": "(416) 555-0678",
        "Preferred Contact Method": "Text message",
        "Best Time to Contact": "Afternoon (12pm-5pm)",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "Rosa Martinez",
        "Emergency Contact Relationship": "Parent/Guardian",
        "Emergency Contact Phone": "(416) 555-0679",
        "Referral Source": "School/Education",
    },
    "DEMO-007": {
        "Preferred Name": "Maya",
        "Primary Phone": "(905) 555-0789",
        "Preferred Contact Method": "Phone call",
        "Best Time to Contact": "Morning (9am-12pm)",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "David Thompson",
        "Emergency Contact Relationship": "Parent/Guardian",
        "Emergency Contact Phone": "(905) 555-0790",
        "Referral Source": "Hospital/Health provider",
        "Accommodation Needs": "Needs quiet space for meetings; social anxiety",
    },
    "DEMO-008": {
        "Primary Phone": "(647) 555-0890",
        "Preferred Contact Method": "Text message",
        "Best Time to Contact": "Evening (5pm-8pm)",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "Lisa Nguyen",
        "Emergency Contact Relationship": "Parent/Guardian",
        "Emergency Contact Phone": "(647) 555-0891",
        "Referral Source": "Social services (OW/ODSP)",
    },
    "DEMO-009": {
        "Preferred Name": "Zara",
        "Primary Phone": "(416) 555-0901",
        "Email": "zara.a@example.com",
        "Preferred Contact Method": "Email",
        "Best Time to Contact": "Afternoon (12pm-5pm)",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "Fatima Ahmed",
        "Emergency Contact Relationship": "Parent/Guardian",
        "Emergency Contact Phone": "(416) 555-0902",
        "Referral Source": "Self-referral",
    },
    "DEMO-010": {
        "Preferred Name": "Liam",
        "Primary Phone": "(905) 555-1012",
        "Email": "liam.oconnor@example.com",
        "Preferred Contact Method": "Phone call",
        "Best Time to Contact": "Any time",
        "Preferred Language of Service": "English",
        "Emergency Contact Name": "Patrick O'Connor",
        "Emergency Contact Relationship": "Parent/Guardian",
        "Emergency Contact Phone": "(905) 555-1013",
        "Referral Source": "Community agency",
        "Referring Agency Name": "Youth Employment Services",
    },
}
