# Generated by Django 6.0.1 on 2026-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo users see demo data only. Set at creation, never changed.'),
        ),
    ]
