# Generated by Django 6.0.1 on 2026-02-05 16:27

from django.db import migrations


def set_demo_flag_for_users(apps, schema_editor):
    """Set is_demo=True for all User records where username starts with 'demo-'."""
    User = apps.get_model('auth_app', 'User')
    User.objects.filter(username__istartswith='demo-').update(is_demo=True)


def reverse_demo_flag_for_users(apps, schema_editor):
    """Reverse: set is_demo=False for users with username starting with 'demo-'."""
    User = apps.get_model('auth_app', 'User')
    User.objects.filter(username__istartswith='demo-').update(is_demo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_add_is_demo_field'),
    ]

    operations = [
        migrations.RunPython(set_demo_flag_for_users, reverse_demo_flag_for_users),
    ]
