# Generated by Django 6.0.1 on 2026-02-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_set_demo_flag_on_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, default='', help_text='Stored on login. Empty = use cookie/session preference.', max_length=10),
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('receptionist', 'Front Desk'), ('staff', 'Direct Service'), ('program_manager', 'Program Manager'), ('executive', 'Executive'), ('admin', 'Administrator')], max_length=20),
        ),
    ]
