# Generated by Django 6.0.1 on 2026-02-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_demo_context',
            field=models.BooleanField(default=False, help_text='True when the action was performed by a demo user.'),
        ),
    ]
