# Generated by Django 5.1.15 on 2026-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_add_cancel_action_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged in'), ('login_failed', 'Login failed'), ('logout', 'Logged out'), ('export', 'Exported'), ('view', 'Viewed'), ('post', 'Created'), ('put', 'Updated'), ('patch', 'Updated'), ('access_denied', 'Access denied'), ('cancel', 'Cancelled')], max_length=50),
        ),
    ]
