# Generated by Django 6.0.1 on 2026-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo clients are only visible to demo users. Set at creation, never changed.'),
        ),
    ]
