# Generated by Django 6.0.1 on 2026-02-05 16:27

from django.db import migrations


def set_demo_flag_for_clients(apps, schema_editor):
    """Set is_demo=True for all ClientFile records where record_id starts with 'DEMO-'."""
    ClientFile = apps.get_model('clients', 'ClientFile')
    ClientFile.objects.filter(record_id__istartswith='DEMO-').update(is_demo=True)


def reverse_demo_flag_for_clients(apps, schema_editor):
    """Reverse: set is_demo=False for clients with record_id starting with 'DEMO-'."""
    ClientFile = apps.get_model('clients', 'ClientFile')
    ClientFile.objects.filter(record_id__istartswith='DEMO-').update(is_demo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_is_demo_field'),
    ]

    operations = [
        migrations.RunPython(set_demo_flag_for_clients, reverse_demo_flag_for_clients),
    ]
