# Generated by Django 5.1.15 on 2026-02-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_rename_cross_programme_to_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='cross_program_sharing_consent',
            field=models.BooleanField(default=False, help_text='Client has given express consent for clinical information to be shared across programs. Required under PHIPA for multi-program agencies.'),
        ),
    ]
