# Generated by Django 5.1.15 on 2026-02-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_staffportalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='_email_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='consent_messaging_type',
            field=models.CharField(blank=True, choices=[('express', 'Express'), ('implied', 'Implied')], default='express', max_length=10),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='consent_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='email_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='email_consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='email_consent_withdrawn_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='has_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='has_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='phone_last_confirmed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('sms', 'Text Message'), ('email', 'Email'), ('both', 'Both'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='sms_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='sms_consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='sms_consent_withdrawn_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
