# Generated by Django 6.0.1 on 2026-02-05 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureExportLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('export_type', models.CharField(choices=[('client_data', 'Client Data'), ('metrics', 'Metric Report'), ('cmt', 'CMT Report')], max_length=50)),
                ('filters_json', models.TextField(default='{}')),
                ('client_count', models.PositiveIntegerField()),
                ('includes_notes', models.BooleanField(default=False)),
                ('recipient', models.CharField(max_length=200)),
                ('filename', models.CharField(default='export.csv', max_length=255)),
                ('is_elevated', models.BooleanField(default=False)),
                ('admin_notified_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_links', to=settings.AUTH_USER_MODEL)),
                ('last_downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_exports', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='reports_sec_expires_1ec1f3_idx'), models.Index(fields=['created_by', 'created_at'], name='reports_sec_created_5eb283_idx')],
            },
        ),
    ]
