# Generated by Django 5.2.5 on 2026-02-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_funder_profiles"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FunderProfile",
            new_name="ReportTemplate",
        ),
        migrations.RenameField(
            model_name="demographicbreakdown",
            old_name="funder_profile",
            new_name="report_template",
        ),
        migrations.AlterModelTable(
            name="reporttemplate",
            table="report_templates",
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_report_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Programs linked to this reporting template.",
                related_name="report_templates",
                to="programs.program",
            ),
        ),
    ]
