# Generated by Django 5.1.15 on 2026-02-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rename_funder_profile_to_report_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(help_text="Template name, e.g., 'United Way Greater Toronto'.", max_length=255),
        ),
    ]
